// <auto-generated />
using System;
using HrNew.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HrNew.Persistence.Migrations
{
    [DbContext(typeof(HrManagementDbContext))]
    partial class HrManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HrNew.Domain.HrAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HrAllocations");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Name = "Adam",
                            Surname = "Nowak"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Maciek",
                            Surname = "Bogdan"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Tymon",
                            Surname = "Matison"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Jan",
                            Surname = "Szczur"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Konrad",
                            Surname = "Epal"
                        });
                });

            modelBuilder.Entity("HrNew.Domain.HrRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HrAllocationId")
                        .HasColumnType("int");

                    b.Property<int>("HrTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HrAllocationId");

                    b.HasIndex("HrTypeId");

                    b.ToTable("HrRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description",
                            EndDate = new DateTime(2023, 9, 10, 7, 7, 47, 419, DateTimeKind.Local).AddTicks(5565),
                            HrAllocationId = 101,
                            HrTypeId = 1,
                            StartDate = new DateTime(2023, 9, 10, 7, 7, 47, 419, DateTimeKind.Local).AddTicks(5538)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description",
                            EndDate = new DateTime(2023, 9, 10, 7, 7, 47, 419, DateTimeKind.Local).AddTicks(5569),
                            HrAllocationId = 102,
                            HrTypeId = 2,
                            StartDate = new DateTime(2023, 9, 10, 7, 7, 47, 419, DateTimeKind.Local).AddTicks(5568)
                        });
                });

            modelBuilder.Entity("HrNew.Domain.HrType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HrTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vacation"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sick"
                        });
                });

            modelBuilder.Entity("HrNew.Domain.HrRequest", b =>
                {
                    b.HasOne("HrNew.Domain.HrAllocation", "HrAllocation")
                        .WithMany()
                        .HasForeignKey("HrAllocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HrNew.Domain.HrType", "HrType")
                        .WithMany()
                        .HasForeignKey("HrTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HrAllocation");

                    b.Navigation("HrType");
                });
#pragma warning restore 612, 618
        }
    }
}
